### ISSUE TITLE
gather script

### ISSUE THREAD

**Issue by vartaxe** [paulwetter/WettersSource#1]
hi,

having issues with the gather script here

![image](https://user-images.githubusercontent.com/11176349/59600104-8cd04e00-9100-11e9-97c2-7da2014bf42d.png)
wetehr run from ts or not it will output the same errors...

any help would be appreciated thanks.

ps: would be nice if it could report if the device is on wifi and perhaps if a usb drive is present or a docking station like dell tb16

**Comment by paulwetter** [comment]
If you are getting that error either way, then it means that "Microsoft.SMS.TSEnvironment" is not available for some reason.  That is very odd.
1. What type of TS are you running?
2. SCCM Version?
3. PE Version?

Also, can you run though Niehaus' blog here to see if you can dump all the TS variables?  If you cannot, than there is a bigger issue going on for you. https://blogs.technet.microsoft.com/mniehaus/2010/04/26/dumping-task-sequence-variables/

PS: Put your PS in as a separate issue and I'll see what I can do.

**Comment by paulwetter** [comment]
No Response, closing
